
# SEO settings
title: "Tomas"
title2: "Kulvietis" # default: ""
description: "Personal website of Tomas Kulvietis."
keywords: "SEO, blog, web, minimalist, Software Developer, C#, .NET, University of Nottingham, Computer Science, Student, Programming, Placements"
url: https://tomaskul.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/tomaskul/tomaskul.github.io
disqus_shortname: ""
twitter_username: "tomas__tweets"
comments: false

# Build settings
permalink   : /:year/:title/
highlighter : rouge
markdown    : kramdown
extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Tomas Kulvietis"
  job      : "Software Developer"
  bio      : "Check out some my past projects."
  thumb    : /assets/images/me.png
  email    : 
  url      : https://tomaskul.github.io
  github   : https://github.com/tomaskul
  twitter  : https://twitter.com/tomas__tweets
  facebook : 
  linkedin : https://www.linkedin.com/in/tomas-kulvietis/

# social settings
og_locale: "en_UK"
twitter_card: "summary_large_image"
twitter_site: "@tomas__tweets"

plugins:
  - bourbon
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-pandoc

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
